/**
 * REST contracts shared by the Axios client and the MSW handlers, so the
 * mock server and the app can never disagree on a shape.
 *
 *   POST /api/matches                       register a finished match (idempotent by matchId)
 *   GET  /api/ranking?configKey&page&pageSize
 *   GET  /api/players/:playerId/matches?page&pageSize
 */

export type EndReason = 'time_up' | 'defeated';

export interface MatchConfigDto {
  sessionSeconds: number;
  spawnIntervalSeconds: number;
  rulesetVersion: number;
}

export interface MatchSubmission {
  /** Generated by the client when the match starts; doubles as the idempotency key. */
  matchId: string;
  playerId: string;
  playerName: string;
  /** ISO timestamp of when the match ended. */
  playedAt: string;
  score: number;
  /** Active seconds actually played (pauses excluded). */
  durationSeconds: number;
  endReason: EndReason;
  config: MatchConfigDto;
  /** Deterministic fingerprint of `config`; ranking only compares equal keys. */
  configKey: string;
}

export interface MatchRecord extends MatchSubmission {
  /** Server time when the record was first stored. */
  recordedAt: string;
}

export interface RegisterMatchResponse {
  record: MatchRecord;
  /** False when the matchId was already stored and the existing record was returned. */
  created: boolean;
}

export interface Page<T> {
  items: T[];
  page: number;
  pageSize: number;
  totalItems: number;
  totalPages: number;
  /**
   * Monotonic server data version at the time the response was produced.
   * Lets the client refuse to replace newer data with an older response.
   */
  dataVersion: number;
}

export interface RankingEntry {
  rank: number;
  matchId: string;
  playerId: string;
  playerName: string;
  score: number;
  durationSeconds: number;
  playedAt: string;
}

export interface RankingPage extends Page<RankingEntry> {
  configKey: string;
}

export interface HistoryPage extends Page<MatchRecord> {
  playerId: string;
}

export interface ApiErrorBody {
  error: { code: string; message: string };
}

export const IDEMPOTENCY_HEADER = 'Idempotency-Key';
export const PAGE_SIZE = 5;
